### GET request to example server
POST http://localhost:9000/api/v1/posts?userId=e8a61f05-1f82-4dfd-b36d-145c45f2bde8
Content-Type: application/json

{
  "title": "Test title",
  "body_text": "Pukah"
}

###

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
  "email": "sithiraac@gmail.com",
  "password": "secret"
}

###


GET http://localhost:9000/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdGhpcmFhY0BnbWFpbC5jb20iLCJleHAiOjE3MjExOTQzNjksImZ1bGxfbmFtZSI6IlNpdGhpcmEgTXVuYXNpbmdoZSIsImlhdCI6MTcyMTE5MDc2OSwic3ViamVjdCI6ImU4YTYxZjA1LTFmODItNGRmZC1iMzZkLTE0NWM0NWYyYmRlOCJ9.HPY0J7U7ftpxbGnpA8APFq5rsfCFcHiaRytvti64E3o

###


POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
  "email": "testx@gmail.com",
  "password": "abc@123",
  "password_retyped": "abc@123",
  "first_name": "testtt",
  "last_name": "lastxxxx"
}

###

POST http://localhost:9000/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdGhpcmFhY0BnbWFpbC5jb20iLCJleHAiOjE3MjExOTQzNjksImZ1bGxfbmFtZSI6IlNpdGhpcmEgTXVuYXNpbmdoZSIsImlhdCI6MTcyMTE5MDc2OSwic3ViamVjdCI6ImU4YTYxZjA1LTFmODItNGRmZC1iMzZkLTE0NWM0NWYyYmRlOCJ9.HPY0J7U7ftpxbGnpA8APFq5rsfCFcHiaRytvti64E3o

{
  "title": "Lapdsadsdsa",
  "body_text": "Topadsdsadasdsa"
}

###


PUT http://localhost:9000/api/v1/posts/fd597181-dc4b-422e-804a-2a0657224813
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdGhpcmFhY0BnbWFpbC5jb20iLCJleHAiOjE3MjEyMzA3NzAsImZ1bGxfbmFtZSI6IlNpdGhpcmEgTXVuYXNpbmdoZSIsImlhdCI6MTcyMTIyNzE3MCwic3ViamVjdCI6ImU4YTYxZjA1LTFmODItNGRmZC1iMzZkLTE0NWM0NWYyYmRlOCJ9.gMYr_VTKypdrlBBlSamHsqk1mzf5rhbv9pYO54__m4M

{
  "title": "hahahaha",
  "body_text": "Topadsdsadasdsa"
}

###

DELETE http://localhost:9000/api/v1/posts/fd597181-dc4b-422e-804a-2a0657224813
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdGhpcmFhY0BnbWFpbC5jb20iLCJleHAiOjE3MjEyMzA3NzAsImZ1bGxfbmFtZSI6IlNpdGhpcmEgTXVuYXNpbmdoZSIsImlhdCI6MTcyMTIyNzE3MCwic3ViamVjdCI6ImU4YTYxZjA1LTFmODItNGRmZC1iMzZkLTE0NWM0NWYyYmRlOCJ9.gMYr_VTKypdrlBBlSamHsqk1mzf5rhbv9pYO54__m4M

###

GET http://localhost:9000/api/v1/posts/fd597181-dc4b-422e-804a-2a0657224813
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpdGhpcmFhY0BnbWFpbC5jb20iLCJleHAiOjE3MjEyMzA3NzAsImZ1bGxfbmFtZSI6IlNpdGhpcmEgTXVuYXNpbmdoZSIsImlhdCI6MTcyMTIyNzE3MCwic3ViamVjdCI6ImU4YTYxZjA1LTFmODItNGRmZC1iMzZkLTE0NWM0NWYyYmRlOCJ9.gMYr_VTKypdrlBBlSamHsqk1mzf5rhbv9pYO54__m4M
